version: "3"
services:
  redis:
    restart: always
    image: redis
    ports:
      - "6479:6379"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5532:5432"
    volumes:
      - /srv/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
  outline:
    image: outlinewiki/outline:latest
    restart: always
    env_file:  .env
    ports:
      - "3000:3000"
    command: yarn start --env=production-ssl-disabled